<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Y.Authentication.Application\Y.Authentication.Application.csproj" />
    <ProjectReference Include="..\Y.Authentication.Domain\Y.Authentication.Domain.csproj" />
  </ItemGroup>

</Project>
