<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Y.Authentication.Application\Y.Authentication.Application.csproj" />
    <ProjectReference Include="..\Y.Authentication.Domain\Y.Authentication.Domain.csproj" />
    <ProjectReference Include="..\Y.Authentication.Infrastructure\Y.Authentication.Infrastructure.csproj" />
    <ProjectReference Include="..\Y.Authentication.Presentation\Y.Authentication.Presentation.csproj" />
  </ItemGroup>

</Project>
